### ISSUE TITLE
Use /rapidpro tags

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/rapidpro-docker#8]
Hey guys,

I just wrote quick fab file on our side to push matching tag/shas from the Nyaruka fork to RapidPro. We'll do this whenever we upmerge, so it may make sense to build docker images off of those instead. (/rapidpro tends to be behind /nyaruka but we generally only upmerge when we feel we have a reasonably stable build.

The releases are here: https://github.com/rapidpro/rapidpro/releases

We annotate the release with the same stuff as the CHANGELOG

**Comment by smn** [comment]
Thanks for this! #9 addresses this.

**Comment by smn** [comment]
@nicpottier these tags in nyaruka/rapidpro aren't showing up in rapidpro/rapidpro anymore. Has something changed on your side or should we switch back to nyaruka? The last one was 3.0.45 while nyaruka/rapidpro is on 3.0.49.

**Comment by nicpottier** [comment]
These only show up when we push upstream. We haven't done so since 3.0.45. When we do we'll push the associated tags as well.

If you want the tippy tip, then you should be going against /nyaruka, but that will involve building images for versions with bugs that we fix before we push to /rapidpro. So pick your poison. :)

**Comment by smn** [comment]
Ah, cool, that makes perfect sense. I'll stick to rapidpro/rapidpro, I'll see if I can rework the build matrix to include nyaruka/rapidpro's tags and tag them separately.

**Comment by DavidLemayian** [comment]
Maybe related but should the tags on `docker-compose.yml` be updated to?

https://github.com/rapidpro/rapidpro-docker/blob/master/docker-compose.yml#L9

Possibly the one for `rapidpro` service should use the `.` context?

**Comment by smn** [comment]
Good point, thanks, I'll attend to that.
